# Generated by Django 3.2.7 on 2021-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210909_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('phones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
