# Generated by Django 3.2.7 on 2021-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_broadcastmessage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='facilities',
            field=models.BooleanField(default=False),
        ),
    ]
