# Generated by Django 3.2.7 on 2021-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, choices=[('hiv_aids', 'HIV / AIDS Group'), ('cancer', 'Cancer Group')], max_length=100, null=True),
        ),
    ]
